version: "3.5"
services:
  app:
    stdin_open: true
    tty: true
    build: .
    ports:
      - 8000:8000
    volumes:
      - ".:/home/student/projobj"
      - "/home/student/projobj/project/vendor" #ignore to work faster, but have to copy manually

# docker cp vendor <cont_name>:/home/student/projobj/project