version: '3.4'

services:
  nodejsexpresstemplate:
    image: nodejsexpresstemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
